# Generated by Django 3.1.2 on 2020-10-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
            ],
        ),
    ]
