# Generated by Django 3.1.2 on 2020-10-13 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0003_customers_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='ConfirmPassword',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='Password',
        ),
        migrations.AddField(
            model_name='customers',
            name='Address',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='customers',
            name='Calories',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Email',
            field=models.EmailField(default='test@gmail.com', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ProfilePic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
