# Generated by Django 3.0 on 2020-10-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20201013_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Address',
            field=models.CharField(default='Nepal', max_length=30),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
