# Generated by Django 3.1.2 on 2020-10-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20201013_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='Email',
        ),
        migrations.AlterField(
            model_name='customers',
            name='Address',
            field=models.CharField(default='Nepal', max_length=30),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ProfilePic',
            field=models.ImageField(blank=True, default='/Static/images/3.jpg', null=True, upload_to=''),
        ),
    ]
