# Generated by Django 3.1.2 on 2020-10-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20201016_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ProfilePic',
            field=models.ImageField(blank=True, default='/9.png', null=True, upload_to=''),
        ),
    ]
