# Generated by Django 3.1.2 on 2020-10-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_calculations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationsbmi',
            name='BMI',
            field=models.DecimalField(decimal_places=16, max_digits=18),
        ),
    ]
