# Generated by Django 3.1.2 on 2020-10-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_calculations', '0002_auto_20201018_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationsbmi',
            name='BMI',
            field=models.FloatField(),
        ),
    ]
