# Generated by Django 3.1.2 on 2020-10-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_calculations', '0003_auto_20201018_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculationsbmi',
            old_name='BMI',
            new_name='BMR',
        ),
    ]
