# Generated by Django 3.1.2 on 2020-10-18 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diet_calculations', '0004_auto_20201018_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationsbmi',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
