# Generated by Django 3.1.2 on 2020-10-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_calculations', '0006_calculationsbdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsbmi',
            name='field',
            field=models.CharField(default='BMR', max_length=20),
        ),
    ]
