# Generated by Django 3.1.2 on 2020-10-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_calculations', '0007_calculationsbmi_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationsbdi',
            name='field',
            field=models.CharField(default='BDI', max_length=20),
        ),
    ]
