# Generated by Django 3.1.2 on 2020-10-21 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diet_calculations', '0008_calculationsbdi_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BMR', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('field', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='calculationsbmi',
            name='user',
        ),
        migrations.DeleteModel(
            name='CalculationsBDI',
        ),
        migrations.DeleteModel(
            name='CalculationsBMI',
        ),
    ]
