# Generated by Django 3.1.2 on 2020-10-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_calculations', '0009_auto_20201021_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculations',
            old_name='field',
            new_name='fieldname',
        ),
    ]
