# Generated by Django 3.1.2 on 2020-10-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_calculations', '0011_auto_20201021_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='BMR',
            field=models.FloatField(default=None, null=True),
        ),
    ]
